# 基础镜像: alg_base_ubuntu_samll_amd64_gpu:1.0.0
# ubuntu 20
# Package                        Version
# ------------------------------ ---------
# absl-py                        0.15.0
# astunparse                     1.6.3
# cachetools                     4.2.4
# certifi                        2021.10.8
# charset-normalizer             2.0.7
# clang                          5.0
# flatbuffers                    1.12
# gast                           0.4.0
# GDAL                           3.3.0
# google-auth                    2.3.0
# google-auth-oauthlib           0.4.6
# google-pasta                   0.2.0
# grpcio                         1.41.0
# h5py                           3.1.0
# idna                           3.3
# keras                          2.6.0
# Keras-Preprocessing            1.1.2
# Markdown                       3.3.4
# numpy                          1.19.5
# oauthlib                       3.1.1
# opencv-contrib-python-headless 4.5.3.56
# opt-einsum                     3.3.0
# pip                            20.0.2
# protobuf                       3.18.1
# pyasn1                         0.4.8
# pyasn1-modules                 0.2.8
# PyYAML                         5.4.1
# requests                       2.26.0
# requests-oauthlib              1.3.0
# rsa                            4.7.2
# setuptools                     45.2.0
# six                            1.15.0
# tensorboard                    2.7.0
# tensorboard-data-server        0.6.1
# tensorboard-plugin-wit         1.8.0
# tensorflow-estimator           2.6.0
# tensorflow-gpu                 2.6.0
# termcolor                      1.1.0
# typing-extensions              3.7.4.3
# urllib3                        1.26.7
# Werkzeug                       2.0.2
# wheel                          0.37.0
# wrapt                          1.12.1

FROM osgeo/gdal:ubuntu-small-latest-amd64
ENV is_prod_env=True

RUN mkdir -p /app \
&& mkdir -p /data_mining/data  \
&& mkdir -p /data_mining/result \
&& mkdir -p /data_mining/logs \
&& mkdir -p /data_mining/shp \
&& mkdir -p /data_mining/model \
&& sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
&& sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
&& apt-get update \
&& sh -c '/bin/echo -e "Y\n" | apt-get  install python3-pip' \
&& sh -c '/bin/echo -e "Y\n" | apt-get install libgl1-mesa-glx' \
&& pip3 install -i https://pypi.mirrors.ustc.edu.cn/simple/ --no-cache-dir opencv-contrib-python-headless==4.5.3.56 requests==2.26.0 PyYAML==5.4.1 \
&& pip3 install --upgrade -i https://pypi.mirrors.ustc.edu.cn/simple/ --no-cache-dir numpy==1.21.2 \
&& curl -o /tmp/libcudart11.0_11.3.109~11.3.1-4_amd64.deb  http://mirrors.ustc.edu.cn/ubuntu/pool/multiverse/n/nvidia-cuda-toolkit/libcudart11.0_11.3.109~11.3.1-4_amd64.deb \
&& dpkg -i /tmp/libcudart11.0_11.3.109~11.3.1-4_amd64.deb \
&& pip3 install -i https://pypi.mirrors.ustc.edu.cn/simple/ --no-cache-dir tensorflow-gpu  \
&& pip3 install -i https://pypi.mirrors.ustc.edu.cn/simple/ --no-cache-dir Keras \
&& apt-get clean &&  apt-get autoclean